baseURL = 'https://prismers.github.io/ClearAgent/'
languageCode = 'en-us'
title = 'ClearAgent'
# Automatically generate robots.txt
enableRobotsTXT = true
theme = "gokarna"

[params]
description = 'Agentic Binary Analysis'
socialIcons = [{ name = "github", url = "" }, { name = "arxiv", url = "" }]

[menu]
[[menu.main]]
name = 'Home'
url = '/'
weight = 1

[[menu.main]]
name = 'News'
url = '/news/'
weight = 2

[[menu.main]]
name = 'Bugs'
url = '/bugs/'
weight = 3

[[menu.main]]
name = 'Demo'
url = '/demo/'
weight = 4
